baseURL = 'https://mkerle.dev/'
languageCode = 'en-us'
title = 'morgan'
theme = 'hugo-theme-console'

[params]


  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
